if(NOT DEFINED RK3588_SDK_ROOT)
  set(RK3588_SDK_ROOT "$ENV{RK3588_SDK_ROOT}")
endif()
if(NOT RK3588_SDK_ROOT)
  message(FATAL_ERROR "Set RK3588_SDK_ROOT to the Rockchip SDK root")
endif()
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RK3588_SDK_ROOT)
set(_toolchain_root "${RK3588_SDK_ROOT}/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu")
set(_sysroot "${_toolchain_root}/aarch64-none-linux-gnu/libc")
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER "${_toolchain_root}/bin/aarch64-none-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${_toolchain_root}/bin/aarch64-none-linux-gnu-g++")
set(CMAKE_SYSROOT "${_sysroot}")
set(CMAKE_FIND_ROOT_PATH "${_sysroot};${RK3588_SDK_ROOT}/debian/binary")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(OpenCV_DIR "${RK3588_SDK_ROOT}/external/rknpu2/examples/3rdparty/opencv/opencv-linux-aarch64/share/OpenCV" CACHE PATH "")
